### ISSUE TITLE
Error 404 when downloading TikTok videos of some users

### ISSUE THREAD

**Issue by djmarioka** [snlbaral/tiktok-dl#1]
Hi,

I have this error: **ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output**
![2021-06-05 08_21_36-New Issue · snlbaral_tiktok-dl](https://user-images.githubusercontent.com/81478245/120882310-18399700-c5d7-11eb-8d35-cd1981471724.png)

when I try to download some Tik Tok user's videos, I attach a screenshot of the issue. 

As I say, it's not always but pretty frequently this issue happens.

Could you fix it?.

Thanks.

**Comment by snlbaral** [comment]
> Hi,
> 
> I have this error: **ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output**
> ![2021-06-05 08_21_36-New Issue · snlbaral_tiktok-dl](https://user-images.githubusercontent.com/81478245/120882310-18399700-c5d7-11eb-8d35-cd1981471724.png)
> 
> when I try to download some Tik Tok user's videos, I attach a screenshot of the issue.
> 
> As I say, it's not always but pretty frequently this issue happens.
> 
> Could you fix it?.
> 
> Thanks.

The error seems to be for videos that are not directly accessible through URL. when we open such videos from Tiktok, it does play but if you refresh the browser, it says "Video currently unavailable". Until we find a fix for this. I have put 'ignoreerrors' to download method. It will ignore any such errors and continue to download next video rather than exiting.
