### ISSUE TITLE
ERROR:root:Tiktok wants to display a catcha

### ISSUE THREAD

**Issue by djmarioka** [snlbaral/tiktok-dl#2]
Hi,

there's a new issue from yesterday, it says:

**ERROR:root:Tiktok wants to display a catcha. Response is:

..........

TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters**

![ERROR TIKTOK-DL](https://user-images.githubusercontent.com/81478245/121143741-a9aa4280-c83d-11eb-8629-3746fa826fd0.png)

 

Could you fix it?. 

Thanks.

**Comment by snlbaral** [comment]
The API used for this seems like having some issue. until then use the tiktok-auto.py. also install the modules with requirements.txt.
