### ISSUE TITLE
How to download all videos?

### ISSUE THREAD

**Issue by Mayaman5566** [snlbaral/tiktok-dl#3]
tiktok.py can download user all video
but tiktok-auto.py only download the latest 6 videos, not tiktok user all videos
How should I setting code?
Thanks and Regards,

**Comment by snlbaral** [comment]
run the script. it will open new tab in the browser, do not close or minimize that browser window/tab. let it scroll to bottom. make sure you have good internet connection.

**Comment by Mayaman5566** [comment]
I observe
doesn't seem to scroll to bottom
but It's okay I can still use tiktok.py
thank u !

**Comment by snlbaral** [comment]
it was due to captcha disabled the scroll. I have resolved that issue to wait until captcha is resolved by user before scrolling.
